### ISSUE TITLE
Missing Staging icon

### ISSUE THREAD

**Issue by kleineroscar** [HiromuHota/pdi-git-plugin#42] opened 2020-08-27 07:23 UTC
Hey there,

It seems like the plugin is not loading the staging icon for me. 
I'm using PDI 9.0.0.0-423 on Windows.
I have tried both the marketplace version and a direct download here from github.

![image](https://user-images.githubusercontent.com/18505853/91410040-9302a400-e846-11ea-9e94-0cf7a5690900.png)

**Comment by HiromuHota** [comment] 2020-08-27 22:37
@kleineroscar Thank you for reporting! I was able to reproduce this issue.
The black rectangle actually meant to be a checkbox.
Although it does not show whether it is checked or not, you can actually check it to stage the file (and uncheck to unstage).
Please use this workaround until I fix it.

**Comment by HiromuHota** [comment] 2020-08-27 22:49
Turns out that this issue comes from PDI itself (https://jira.pentaho.com/browse/PDI-18497) and a fix will be available 9.1.0 GA.

**Comment by HiromuHota** [comment] 2020-08-27 22:50
Close as this is a duplicate of https://jira.pentaho.com/browse/PDI-18497.

**Closed by HiromuHota** 2020-08-27 22:50 UTC
